In [1]:
import logging
import pandas as pd
from iso3166 import countries

from csv import QUOTE_NONNUMERIC
from unicef_schools_attribute_cleaning.pandas.dataframe_cleaner import dataframe_cleaner

# make INFO logs visible
logging.basicConfig(level=logging.INFO)

In [2]:
src_df = pd.read_csv('../../data/UNICE_schools_raw_2020_Jun/usaid_schools.csv', low_memory=False)
src_df

,Region,county_id,county,county_code,subCounty_id,subCounty,subsCounty_code,zone_id,zone,zone_code,school_id,school,verified_latitude,verified_longitude,school_code,tusome_code,REGULAR / SNE,PUBLIC / APBET / HI / VI / HI&VI,2019_Active / Inactive status
0,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,NaN,Chebunyor,NaN,NaN,13.0,1101013.0,REGULAR,PUBLIC,Active
1,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,9CWwjhDS,Kabarbarma,-1.259261,36.803921,1.0,1101001.0,REGULAR,PUBLIC,Active
2,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,R2wzR2g4,Kabochony,0.440002,35.800895,2.0,1101002.0,REGULAR,PUBLIC,Active
3,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,nemmFtXC,Kapkiai,0.426389,35.805504,3.0,1101003.0,REGULAR,PUBLIC,Active
4,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,NaN,Kapkoimet,NaN,NaN,14.0,1101014.0,REGULAR,PUBLIC,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26115,Nairobi,YFZjN4qd,Nyandarua,35,cSaQj4aa,Nyandarua West,7,UEnbPUHp,Ol Joro Orok,2,VXhwMAjT,Riverside,0.011700,36.357299,24.0,35702024.0,REGULAR,PUBLIC,Active
26116,Nairobi,YFZjN4qd,Nyandarua,35,cSaQj4aa,Nyandarua West,7,UEnbPUHp,Ol Joro Orok,2,Pw4HvM8t,Uhuru,-0.143029,36.311293,25.0,35702025.0,REGULAR,PUBLIC,Active
26117,Nairobi,YFZjN4qd,Nyandarua,35,cSaQj4aa,Nyandarua West,7,UEnbPUHp,Ol Joro Orok,2,paM6wjfP,Uiguano,-0.173542,36.385639,26.0,35702026.0,REGULAR,PUBLIC,Active
26118,Nairobi,YFZjN4qd,Nyandarua,35,cSaQj4aa,Nyandarua West,7,UEnbPUHp,Ol Joro Orok,2,3xxcCXh6,Weru,-0.139374,36.380180,27.0,35702027.0,REGULAR,PUBLIC,Active
26119,Nairobi,YFZjN4qd,Nyandarua SNE,35,xQaGMtX9,Nyandarua South,6,9AAtWvX4,Engineer,1,zrqwvsSx,Nyandarua Sch For Deaf,NaN,NaN,17.0,35601017.0,SNE,HI,Active

In [3]:
src_df.columns

Index(['Region', 'county_id', 'county', 'county_code', 'subCounty_id',
       'subCounty', 'subsCounty_code', 'zone_id', 'zone', 'zone_code',
       'school_id', 'school', 'verified_latitude', 'verified_longitude',
       'school_code', 'tusome_code', 'REGULAR / SNE',
       'PUBLIC / APBET / HI / VI / HI&VI', '2019_Active / Inactive status'],
      dtype='object')

In [4]:
# Problem: there are columns 'REGULAR / SNE' and 'PUBLIC / APBET / HI / VI / HI&VI', which look like possibly SchoolType field(s), but 
# it's hard to say without knowledge of the data source. The dataframe_cleaner will just skip those columns because they do not match the schema.
src_df['PUBLIC / APBET / HI / VI / HI&VI'].unique()

array(['PUBLIC', 'HI', 'HI&VI', 'VI', 'MH', 'APBET', 'MD'], dtype=object)

In [5]:
country = countries.get('KE')
with open('kenya_usaid_columns_report.txt', mode='w', encoding='utf-8') as filehandle:
    df = dataframe_cleaner(
        dataframe=src_df,
        country=country,
        removed_columns_report=filehandle,
        is_private=True,
        provider='USAID',
        provider_is_private=True
    )
df

INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:copying dataframe...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:standardizing column names...
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:uuid column not found, generating uuid4
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:renaming columns: {'county': 'admin2',
 'school': 'name',
 'verified_latitude': 'lat',
 'verified_longitude': 'lon'}
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:adding 41 columns from schema: ['admin0',
 'admin1',
 'admin3',
 'admin4',
 'admin_code',
 'admin_id',
 'address',
 'address2',
 'phone_number',
 'person_contact',
 'email',
 'postal_code',
 'altitude',
 'gps_confidence',
 'date',
 'num_students',
 'num_teachers',
 'connectivity',
 'type_connectivity',
 'speed_connectivity',
 'latency_connectivity',
 'availability_connectivity',
 'num_computers',
 'type_school',
 'educ_level',
 'environment',
 'num_classrooms',
 'num_sections',
 'water',
 'electricity',
 'num_latrines',
 'description',
 'last_update',
 'tower_dist',
 'tower_type_service',
 'tower_type',
 'tower_code',
 'tower_latitude',
 'tower_longitude',
 'is_invalid',
 'is_invalid_reason']
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:removing columns: ['Region',
 'county_id',
 'county_code',
 'subCounty_id',
 'subCounty',
 'subsCounty_code',
 'zone_id',
 'zone',
 'zone_code',
 'school_id',
 'school_code',
 'tusome_code',
 'REGULAR / SNE',
 'PUBLIC / APBET / HI / VI / HI&VI',
 '2019_Active / Inactive status'] (not in School schema)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:validate each school row to the schema...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:lookup GADM areas by lat,lon...
INFO:unicef_schools_attribute_cleaning.geocoding.GADMLoader:cache hit for: https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_KEN_gpkg.zip
INFO:unicef_schools_attribute_cleaning.geocoding.GADMLoader:converting geopackage file...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:processing each lat,lon into GADM area...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Kebee, lat,lng=-2.356542985,61.43301773 https://www.openstreetmap.org/#map=18/-2.356542985/61.43301773 (uuid=ca5b0ed1-78b7-42aa-a37a-d985f4c306c3)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=Kebee, lat,lng=-2.356542985,61.43301773 https://www.openstreetmap.org/#map=18/-2.356542985/61.43301773 (uuid=ca5b0ed1-78b7-42aa-a37a-d985f4c306c3)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Eymole, lat,lng=4.038103104,40.20059204 https://www.openstreetmap.org/#map=18/4.038103104/40.20059204 (uuid=d66702a6-1e52-4407-b3f0-ef061504896a)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Bulla Haji, lat,lng=3.97890079,41.73023987 https://www.openstreetmap.org/#map=18/3.97890079/41.73023987 (uuid=c01483e1-e49a-4579-87ee-b7dfe143e3db)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Bur Abor, lat,lng=3.972144842,41.71055603 https://www.openstreetmap.org/#map=18/3.972144842/41.71055603 (uuid=4d987275-da1f-4b7c-8ce4-5e4958b8da02)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Fikow, lat,lng=3.9734256269999997,41.74069977 https://www.openstreetmap.org/#map=18/3.9734256269999997/41.74069977 (uuid=6ea27739-65e8-4575-aafe-29b80f6395b5)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Khalalio, lat,lng=3.9647348719999997,41.61724726 https://www.openstreetmap.org/#map=18/3.9647348719999997/41.61724726 (uuid=2110141d-71fe-4d1d-886b-3ecf381d8c50)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Al Khulafau Rashidin, lat,lng=3.531411409,39.06281281 https://www.openstreetmap.org/#map=18/3.531411409/39.06281281 (uuid=0a732d84-f20f-4424-98cb-30f19b9d5d3f)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Sessi, lat,lng=3.525381883,39.04364395 https://www.openstreetmap.org/#map=18/3.525381883/39.04364395 (uuid=ad8788d4-8c02-43ae-8ab5-120c8735e826)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Somare, lat,lng=3.526919603,39.03312302 https://www.openstreetmap.org/#map=18/3.526919603/39.03312302 (uuid=dfc638fc-5fda-4ba7-b0ef-cbd7d23184dd)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Qicha, lat,lng=3.6265597339999998,38.51463699 https://www.openstreetmap.org/#map=18/3.6265597339999998/38.51463699 (uuid=658cc142-54ee-4c20-b4b2-f8a460f4511f)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Qiltipe, lat,lng=3.652385712,38.52610779 https://www.openstreetmap.org/#map=18/3.652385712/38.52610779 (uuid=24bbb187-7c21-4cea-9709-92798e7bfaf7)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Christ The King Waye Godha, lat,lng=3.606635475,38.69093781 https://www.openstreetmap.org/#map=18/3.606635475/38.69093781 (uuid=26482764-bf61-49a2-9585-862a2556f5ef)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Ringiti, lat,lng=-0.457202196,33.93155289 https://www.openstreetmap.org/#map=18/-0.457202196/33.93155289 (uuid=049e69ff-e9d5-4478-83b6-5f899a710b06)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Ugunja, lat,lng=8.743303298999999,53.04792786 https://www.openstreetmap.org/#map=18/8.743303298999999/53.04792786 (uuid=e340d8d8-c40e-47c7-bcb5-db32cc42a910)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=Ugunja, lat,lng=8.743303298999999,53.04792786 https://www.openstreetmap.org/#map=18/8.743303298999999/53.04792786 (uuid=e340d8d8-c40e-47c7-bcb5-db32cc42a910)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Lyaduywa, lat,lng=0.042980049000000006,17.35349464 https://www.openstreetmap.org/#map=18/0.042980049000000006/17.35349464 (uuid=5d72c8a1-7e38-42dd-a8a1-b444af9f600b)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=Lyaduywa, lat,lng=0.042980049000000006,17.35349464 https://www.openstreetmap.org/#map=18/0.042980049000000006/17.35349464 (uuid=5d72c8a1-7e38-42dd-a8a1-b444af9f600b)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=Mwachema, lat,lng=-4.641280173999999,39.75403214 https://www.openstreetmap.org/#map=18/-4.641280173999999/39.75403214 (uuid=0f42949a-5186-4afd-8841-d43a3fcf82a7)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=Mwachema, lat,lng=-4.641280173999999,39.75403214 https://www.openstreetmap.org/#map=18/-4.641280173999999/39.75403214 (uuid=0f42949a-5186-4afd-8841-d43a3fcf82a7)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:5739 invalid records found. See column is_invalid_reason for details.
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:readying pandas data types...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:done

,address,address2,admin0,admin1,admin2,admin3,admin4,admin_code,admin_id,altitude,...,tower_code,tower_dist,tower_latitude,tower_longitude,tower_type,tower_type_service,type_connectivity,type_school,uuid,water
0,None,None,NaN,NaN,NaN,NaN,None,NaN,"3.6,KEN,GID_3=nan",None,...,None,None,None,None,None,None,None,None,44177c9a-000b-4d89-bf46-5c71debcef9f,<NA>
1,None,None,Kenya,Nairobi,Westlands,Parklands/Highridge,None,KEN.30.17.5_1,"3.6,KEN,GID_3=KEN.30.17.5_1",None,...,None,None,None,None,None,None,None,None,4f08f78b-0c4c-40ca-8d86-6bd3fb526cd7,False
2,None,None,Kenya,Baringo,Baringo Central,Ewalel/Chapchap,None,KEN.1.2.1_1,"3.6,KEN,GID_3=KEN.1.2.1_1",None,...,None,None,None,None,None,None,None,None,e4caf20d-d1a9-4fe3-ae13-f2e4d0aca311,False
3,None,None,Kenya,Baringo,Baringo Central,Ewalel/Chapchap,None,KEN.1.2.1_1,"3.6,KEN,GID_3=KEN.1.2.1_1",None,...,None,None,None,None,None,None,None,None,95fd7f9d-655a-4aa7-84ce-c4dea5a08848,False
4,None,None,NaN,NaN,NaN,NaN,None,NaN,"3.6,KEN,GID_3=nan",None,...,None,None,None,None,None,None,None,None,4358620c-1364-4ce6-9b3e-ebe2a5ec5a67,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26115,None,None,Kenya,Nyandarua,Ol Jorok,Gatimu,None,KEN.35.4.3_1,"3.6,KEN,GID_3=KEN.35.4.3_1",None,...,None,None,None,None,None,None,None,None,3b758be8-d9db-4b46-847b-729521ec98c5,False
26116,None,None,Kenya,Nyandarua,Ol Jorok,Charagita,None,KEN.35.4.1_1,"3.6,KEN,GID_3=KEN.35.4.1_1",None,...,None,None,None,None,None,None,None,None,e85365da-8d52-438b-a049-78ec342f715e,False
26117,None,None,Kenya,Nyandarua,Ol Kalou,Rurii,None,KEN.35.5.5_1,"3.6,KEN,GID_3=KEN.35.5.5_1",None,...,None,None,None,None,None,None,None,None,0fbe21b4-b21e-4448-ae18-6d1ed9e01561,False
26118,None,None,Kenya,Nyandarua,Ol Jorok,Weru,None,KEN.35.4.4_1,"3.6,KEN,GID_3=KEN.35.4.4_1",None,...,None,None,None,None,None,None,None,None,a7d5d088-29e9-4f8f-9252-d61835871a64,False
26119,None,None,NaN,NaN,NaN,NaN,None,NaN,"3.6,KEN,GID_3=nan",None,...,None,None,None,None,None,None,None,None,b2b3a327-1fc9-47d5-9550-7e9fde611aae,<NA>

In [6]:
df.to_csv('kenya_usaid_cleaned.csv', quoting=QUOTE_NONNUMERIC, index=False)

In [7]:
# open in LibreOffice, Excel, other
!open kenya_usaid_cleaned.csv