In [103]:
import logging
import pandas as pd
from pandas import Series
from unicef_schools_attribute_cleaning.models.School import School

In [36]:
src_data_dir='../../data/UNICE_schools_raw_2020_Jun'
fixed_data_dir='../../data/unicef_fixed'

### Sierra Leone (SL): Source

In [37]:
df_sierra_leone = pd.read_csv(f'{src_data_dir}/2019_ASC_schools.csv', low_memory=False)
# df_sierra_leone['country_code'] = 'SL'
df_sierra_leone

,duration,enumerator,new_school,idregion,iddistrict,idcouncil,idchiefdom,idward,idsection,idtown,...,geopoint2longitude,geopoint2altitude,geopoint2accuracy,comment_op,formdef_version,key,submissiondate,starttime,endtime,date
0,1740,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SEINGA,SIENGA,...,-10.62374,258.7,5.0,NaN,1.906140e+09,uuid:5cb166c9-05bf-4b8a-94e9-6566c8ee4fcb,6/29/2019 0:25,6/24/2019 9:37,6/24/2019 10:06,6/24/2019 9:37
1,4737,Morison Mohamed Momoh,New School with Paper Questionnaire,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,15,BAIWALA,BAIWALA,...,NaN,NaN,NaN,NaN,1.906140e+09,uuid:ca4fb19e-bed3-4a94-a0d4-c55b69f5d7c9,6/29/2019 0:25,6/24/2019 11:04,6/25/2019 22:08,6/25/2019 11:04
2,2748,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SIENGA,GBAHAMA,...,-10.67104,248.3,5.0,NaN,1.906140e+09,uuid:2872c576-f82e-4896-925a-ad22d1af54f4,6/21/2019 22:50,6/19/2019 12:39,6/19/2019 13:30,6/19/2019 12:40
3,1730,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,BAIWALA,BAIWALLA,...,-10.64993,216.9,5.0,NaN,1.906140e+09,uuid:4b782dd1-9796-4ee0-8f9f-e3902045efdb,6/29/2019 0:25,6/25/2019 10:06,6/25/2019 10:35,6/25/2019 10:06
4,3143,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SIENGA,TAKPOIMA,...,-10.66492,240.3,5.0,NaN,1.906140e+09,uuid:7ff82373-9bbb-4c48-9150-f6081d8d326b,6/21/2019 22:50,6/19/2019 14:36,6/19/2019 15:32,6/19/2019 14:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Sierra Leone: devseed source + uuid

In [39]:
df_sierra_leone_with_uuid = pd.read_csv(f'{fixed_data_dir}/sierra_leone_original_uuid.csv', low_memory=False)
df_sierra_leone_with_uuid

,duration,enumerator,new_school,idregion,iddistrict,idcouncil,idchiefdom,idward,idsection,idtown,...,geopoint2altitude,geopoint2accuracy,comment_op,formdef_version,key,submissiondate,starttime,endtime,date,uuid
0,1740,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SEINGA,SIENGA,...,258.7,5.0,NaN,1.906140e+09,uuid:5cb166c9-05bf-4b8a-94e9-6566c8ee4fcb,6/29/2019 0:25,6/24/2019 9:37,6/24/2019 10:06,6/24/2019 9:37,dbe99e12-5990-4bf1-b8f5-b40a81b805a6
1,4737,Morison Mohamed Momoh,New School with Paper Questionnaire,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,15,BAIWALA,BAIWALA,...,NaN,NaN,NaN,1.906140e+09,uuid:ca4fb19e-bed3-4a94-a0d4-c55b69f5d7c9,6/29/2019 0:25,6/24/2019 11:04,6/25/2019 22:08,6/25/2019 11:04,9f265313-8761-4e61-a289-063de1e0810e
2,2748,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SIENGA,GBAHAMA,...,248.3,5.0,NaN,1.906140e+09,uuid:2872c576-f82e-4896-925a-ad22d1af54f4,6/21/2019 22:50,6/19/2019 12:39,6/19/2019 13:30,6/19/2019 12:40,5ed3a2b5-813f-4c73-a4dd-c31e66345ebb
3,1730,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,BAIWALA,BAIWALLA,...,216.9,5.0,NaN,1.906140e+09,uuid:4b782dd1-9796-4ee0-8f9f-e3902045efdb,6/29/2019 0:25,6/25/2019 10:06,6/25/2019 10:35,6/25/2019 10:06,838ae38d-5992-43de-a735-e01142112de8
4,3143,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SIENGA,TAKPOIMA,...,240.3,5.0,NaN,1.906140e+09,uuid:7ff82373-9bbb-4c48-9150-f6081d8d326b,6/21/2019 22:50,6/19/2019 14:36,6/19/2019 15:32,6/19/2019 14:36,22b2fb16-dd70-42a1-8ca0-fe29ee33c815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d445e618-c422-461c-acc3-cc7b77dbd0a1
11184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c41aa986-8133-453e-839c-31a154affa81
11185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ca497da1-2686-4b34-aa6b-f6ae577e3c75
11186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4fbb21dd-1baa-4e8c-8610-a76d07140e57
11187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,615c68c5-e8d6-47fd-81d0-f205e4c23a5e

In [41]:
# use the uuid as primary key/index
df_sierra_leone_with_uuid.set_index('uuid', inplace=True)
df_sierra_leone_with_uuid

,duration,enumerator,new_school,idregion,iddistrict,idcouncil,idchiefdom,idward,idsection,idtown,...,geopoint2longitude,geopoint2altitude,geopoint2accuracy,comment_op,formdef_version,key,submissiondate,starttime,endtime,date
uuid,,,,,,,,,,,,,,,,,,,,,
dbe99e12-5990-4bf1-b8f5-b40a81b805a6,1740,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SEINGA,SIENGA,...,-10.62374,258.7,5.0,NaN,1.906140e+09,uuid:5cb166c9-05bf-4b8a-94e9-6566c8ee4fcb,6/29/2019 0:25,6/24/2019 9:37,6/24/2019 10:06,6/24/2019 9:37
9f265313-8761-4e61-a289-063de1e0810e,4737,Morison Mohamed Momoh,New School with Paper Questionnaire,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,15,BAIWALA,BAIWALA,...,NaN,NaN,NaN,NaN,1.906140e+09,uuid:ca4fb19e-bed3-4a94-a0d4-c55b69f5d7c9,6/29/2019 0:25,6/24/2019 11:04,6/25/2019 22:08,6/25/2019 11:04
5ed3a2b5-813f-4c73-a4dd-c31e66345ebb,2748,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SIENGA,GBAHAMA,...,-10.67104,248.3,5.0,NaN,1.906140e+09,uuid:2872c576-f82e-4896-925a-ad22d1af54f4,6/21/2019 22:50,6/19/2019 12:39,6/19/2019 13:30,6/19/2019 12:40
838ae38d-5992-43de-a735-e01142112de8,1730,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,BAIWALA,BAIWALLA,...,-10.64993,216.9,5.0,NaN,1.906140e+09,uuid:4b782dd1-9796-4ee0-8f9f-e3902045efdb,6/29/2019 0:25,6/25/2019 10:06,6/25/2019 10:35,6/25/2019 10:06
22b2fb16-dd70-42a1-8ca0-fe29ee33c815,3143,Morison Mohamed Momoh,School on the list,EASTERN,KAILAHUN,KAILAHUN DISTRICT,DEA,17,SIENGA,TAKPOIMA,...,-10.66492,240.3,5.0,NaN,1.906140e+09,uuid:7ff82373-9bbb-4c48-9150-f6081d8d326b,6/21/2019 22:50,6/19/2019 14:36,6/19/2019 15:32,6/19/2019 14:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
d445e618-c422-461c-acc3-cc7b77dbd0a1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c41aa986-8133-453e-839c-31a154affa81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ca497da1-2686-4b34-aa6b-f6ae577e3c75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4fbb21dd-1baa-4e8c-8610-a76d07140e57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615c68c5-e8d6-47fd-81d0-f205e4c23a5e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Sierra Leone: devseed validated locations

In [42]:
df_sierra_leone_fixed = pd.read_csv(f'{fixed_data_dir}/sierra_leone_fixed.csv', low_memory=False)
df_sierra_leone_fixed

# use the uuid as primary key/index
df_sierra_leone_fixed.set_index('uuid', inplace=True)
df_sierra_leone_fixed

,name,name.1,admin1,admin3,admin4,name.2,name.3,lat,lat.1,lon,...,altitude.1,electricity,num_computers,lat.2,lat.3,lon.2,lon.3,altitude.2,altitude.3,date
uuid,,,,,,,,,,,,,,,,,,,,,
dbe99e12-5990-4bf1-b8f5-b40a81b805a6,Name alqudus islamic primary school,Name alqudus islamic primary school,NaN,NaN,NaN,Name alqudus islamic primary school,Name alqudus islamic primary school,7.937449,7.937444,-10.62371,...,258.7,No Electricity,No,7.937449,7.937444,-10.62371,-10.62374,244.6,258.7,6/24/2019 9:37
5ed3a2b5-813f-4c73-a4dd-c31e66345ebb,Name community primary school,Name community primary school,NaN,NaN,NaN,Name community primary school,Name community primary school,7.900226,7.900227,-10.67105,...,248.3,No Electricity,No,7.900226,7.900227,-10.67105,-10.67104,255.7,248.3,6/19/2019 12:40
838ae38d-5992-43de-a735-e01142112de8,Name early childhood care and development centre,Name early childhood care and development centre,NaN,NaN,NaN,Name early childhood care and development centre,Name early childhood care and development centre,7.995894,7.995918,-10.64987,...,216.9,No Electricity,No,7.995894,7.995918,-10.64987,-10.64993,232.7,216.9,6/25/2019 10:06
22b2fb16-dd70-42a1-8ca0-fe29ee33c815,Name kailahun district education council prima...,Name kailahun district education council prima...,NaN,NaN,NaN,Name kailahun district education council prima...,Name kailahun district education council prima...,7.897158,7.897151,-10.66490,...,240.3,No Electricity,No,7.897158,7.897151,-10.66490,-10.66492,236.0,240.3,6/19/2019 14:36
f5ab99be-df8a-41b8-b838-40492175ee1b,Name methodist primary school,Name methodist primary school,NaN,NaN,NaN,Name methodist primary school,Name methodist primary school,7.987804,7.987806,-10.64877,...,226.3,No Electricity,No,7.987804,7.987806,-10.64877,-10.64877,225.8,226.3,6/21/2019 9:46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
056e3b4c-f6e8-48ba-bd66-91126c576d54,Name wilberforce primary municipal school - in...,Name wilberforce primary municipal school - in...,NaN,NaN,NaN,Name wilberforce primary municipal school - in...,Name wilberforce primary municipal school - in...,8.475442,8.476030,-13.26438,...,226.6,No Electricity,No,8.475442,8.476030,-13.26438,-13.26389,230.7,226.6,6/24/2019 14:47
13e3935f-e324-47ba-a7f5-e494bb4d8b27,Name wilberforce primary municipal school infa...,Name wilberforce primary municipal school infa...,NaN,NaN,NaN,Name wilberforce primary municipal school infa...,Name wilberforce primary municipal school infa...,8.476126,8.475997,-13.26389,...,207.9,No Electricity,No,8.476126,8.475997,-13.26389,-13.26384,236.5,207.9,6/24/2019 13:07
a48f026c-9cf6-4fa8-b469-19e586862b71,Name wonderland nursery and preparatory school,Name wonderland nursery and preparatory school,NaN,NaN,NaN,Name wonderland nursery and preparatory school,Name wonderland nursery and preparatory school,8.489423,8.489437,-13.26418,...,77.8,Grid,No,8.489423,8.489437,-13.26418,-13.26411,65.7,77.8,6/21/2019 10:23
2468648d-a322-42b5-9704-72b9591e0fd5,Name wonders international academy preschool,Name wonders international academy preschool,NaN,NaN,NaN,Name wonders international academy preschool,Name wonders international academy preschool,8.464356,8.464320,-13.24265,...,274.7,Grid,No,8.464356,8.464320,-13.24265,-13.24274,275.3,274.7,7/17/2019 14:37
fb615071-1c45-4d58-b94e-df4b17b8d02e,Name wonders international academy preparatory...,Name wonders international academy preparatory...,NaN,NaN,NaN,Name wonders international academy preparatory...,Name wonders international academy preparatory...,8.464455,8.464365,-13.24259,...,294.2,Grid,No,8.464455,8.464365,-13.24259,-13.24274,284.2,294.2,7/17/2019 15:29

In [60]:
df_sierra_leone_fixed.loc['838ae38d-5992-43de-a735-e01142112de8'].lon

-10.64987

In [61]:
df_sierra_leone_with_uuid.loc['838ae38d-5992-43de-a735-e01142112de8'].geopointlongitude

-10.64987

In [47]:
# join on the uuid to confirm no records were added in the fixing workflow.
tmp = .join(df_sierra_leone_with_uuid, lsuffix='_fixed', rsuffix='_source')
tmp
# ^ this is a long operation, but it confirmed the # rows in the join is 9516 (so all the fixed rows uuids are present in the original)

In [ ]:
# we know these columns are numeric and are required,
df_sierra_leone_fixed.to_numeric(df['lat'], errors='coerce')
df.to_numeric(df['lon'], errors='coerce')
df.dropna(subset=['lat', 'lon'], inplace=True)

### Honduras

In [43]:
df_honduras = pd.read_csv(f'{data_dir}/HN-UNICEF-0-government-0.csv', low_memory=False)
df_honduras['country_code'] = 'HN'
df_honduras

,admin2,admin3,school_id,name,educ_level,environment,address,lon,lat,admin4,speed_connectivity,country_code
0,Atlántida,La Ceiba,10100001,ESCUELA GUADALUPE DE QUEZADA,Básica,Urbano,"BARRIO EL CENTRO, AVENIDA SAN ISIDRO",-91.48873,0.00001,NaN,NaN,HN
1,Atlántida,La Ceiba,10100002,JOSE CECILIO DEL VALLE,Básica,Urbano,BELLA VISTA,-86.78323,15.77059,NaN,NaN,HN
2,Atlántida,La Ceiba,10100004,AUGUSTO C COELLO,Básica,Urbano,B INGLES,-86.79567,15.78602,LA CEIBA,0.0,HN
3,Atlántida,La Ceiba,10100005,JOSE TRINIDAD CABAÑAS,Básica,Urbano,LA MERCED,-86.78438,15.77758,LA CEIBA,0.0,HN
4,Atlántida,La Ceiba,10100006,GUSTAVO A CASTAÑEDA,Básica,Urbano,B MEJIA,-86.79670,15.77411,LA CEIBA,0.0,HN
...,...,...,...,...,...,...,...,...,...,...,...,...
17587,NaN,NaN,80100113,NaN,NaN,NaN,NaN,NaN,NaN,DISTRITO CENTRAL,4.0,HN
17588,NaN,NaN,80100203,NaN,NaN,NaN,NaN,NaN,NaN,DISTRITO CENTRAL,4.0,HN
17589,NaN,NaN,150300138,NaN,NaN,NaN,NaN,NaN,NaN,CATACAMAS,4.0,HN
17590,NaN,NaN,150300038,NaN,NaN,NaN,NaN,NaN,NaN,LAS MESETAS,4.0,HN
17591,NaN,NaN,150100179,NaN,NaN,NaN,NaN,NaN,NaN,JUTICALPA,4.0,HN

In [44]:
df_kazakstan = pd.read_csv(f'{data_dir}/KZ-UNICEF-0-Government-0.csv', low_memory=False)
df_kazakstan['country_code'] = 'KZ'
df_kazakstan

,school_id,admin1,admin3,name,educ_level,type_school,speed_connectivity,lat,lon,country_code
0,908,Акмолинская область,Aршалынский район,"Государственное учреждение""Центральная средняя...","малокомплектная школа, общеобразовательная школа",Коммунальная собственность,4.0,50.807155,72.113394,KZ
1,1468,Акмолинская область,Aршалынский район,Вячеславская СШ,"общеобразовательная школа, малокомплектная школа",Коммунальная собственность,8.0,50.996971,72.080400,KZ
2,1447,Акмолинская область,Aршалынский район,Берсуатская СШ,"общеобразовательная школа, малокомплектная школа",Коммунальная собственность,4.0,50.664100,72.117675,KZ
3,685,Акмолинская область,Aршалынский район,Нововладимировская СШ,"общеобразовательная школа, малокомплектная школа",Коммунальная собственность,4.0,51.286983,72.094823,KZ
4,854,Акмолинская область,Aршалынский район,СШ им.Абая,"общеобразовательная школа, малокомплектная школа",Коммунальная собственность,4.0,51.285193,72.090508,KZ
...,...,...,...,...,...,...,...,...,...,...
7405,12817,г.Шымкент,Каратауский район,СШ №72,общеобразовательная школа,Коммунальная собственность,10.0,42.276673,69.595917,KZ
7406,13399,г.Шымкент,Каратауский район,Школа- лицей №89,"общеобразовательная школа, школа-лицей",Коммунальная собственность,10.0,42.407250,69.608764,KZ
7407,12744,г.Шымкент,Каратауский район,СШ №69,общеобразовательная школа,Коммунальная собственность,10.0,42.402063,69.554381,KZ
7408,13307,г.Шымкент,Каратауский район,"Коммунальное государственное учреждение ""Общео...",общеобразовательная школа,Коммунальная собственность,10.0,42.371249,69.724163,KZ
7409,13437,г.Шымкент,Каратауский район,Общеобразовательная вечерняя средняя школа №1,общеобразовательная школа при исправительном у...,Коммунальная собственность,NaN,42.326688,69.572382,KZ

### Kenya (KE)

In [63]:
df_kenya_liquid_source = pd.read_csv(f'{data_dir}/liquid_schools.csv', low_memory=False)
df_kenya_liquid_source['country_code'] = 'KE'
df_kenya_liquid_source

,Name of School,Province,District,County,Latitude,Longitude,Distance(Km),country_code
0,SOUTHEND ACADEMY,WESTERN,BUNGOMA,BUNGOMA,0.562360,34.561880,0.000038,KE
1,JOY SHIRU PRI SCH,NAIROBI,NAIROBI,NAIROBI,-1.265244,36.750676,0.000144,KE
2,ST EDWARDS HIGH SCH,NAIROBI,STAREHE,NaN,-1.272549,36.822084,0.000158,KE
3,NAIVASHA PRI BOARDING,RIFT VALLEY,NAKURU,NAKURU,-0.704300,36.435070,0.000195,KE
4,MLOLONGO PRI SCH,EASTERN,MACHAKOS,MACHAKOS,-1.388401,36.935328,0.000218,KE
...,...,...,...,...,...,...,...,...
32480,DAVA INTEGRATED PRI SCH,NORTH EASTERN,MANDERA,MANDERA,3.953030,41.860900,401.815377,KE
32481,DAVA SPECIAL UNIT,NORTH EASTERN,MANDERA,MANDERA,3.953030,41.860900,401.815377,KE
32482,BORDER VIEW ACADEMY PRI SCH,NORTH EASTERN,MANDERA,MANDERA,3.942400,41.867270,402.275520,KE
32483,BURUBURU PRI SCH,NORTH EASTERN,MANDERA,MANDERA,3.947800,41.868850,402.566618,KE
32484,B.P.ONE PRI SCH,NORTH EASTERN,MANDERA,MANDERA,3.969920,41.886510,404.986109,KE

In [67]:
# load devseed source + uuid
df_kenya_liquid_uuid = pd.read_csv(f'{fixed_data_dir}/kenya_liquid_original_uuid.csv', low_memory=False)
df_kenya_liquid_uuid

# use the uuid as primary key/index
df_kenya_liquid_uuid.set_index('uuid', inplace=True)
df_kenya_liquid_uuid

,Name of School,Province,District,County,Latitude,Longitude,Distance(Km)
uuid,,,,,,,
801dbf2c-c795-4e4d-8e1f-726fbf583c20,SOUTHEND ACADEMY,WESTERN,BUNGOMA,BUNGOMA,0.562360,34.561880,0.000038
0c9a96ac-3c87-4961-b1ee-0f930b4f1a0a,JOY SHIRU PRI SCH,NAIROBI,NAIROBI,NAIROBI,-1.265244,36.750676,0.000144
302367ed-7a50-4069-aa91-7a6a70a779e3,ST EDWARDS HIGH SCH,NAIROBI,STAREHE,NaN,-1.272549,36.822084,0.000158
51baf53c-1aa1-4105-914f-a0cfca56aefb,NAIVASHA PRI BOARDING,RIFT VALLEY,NAKURU,NAKURU,-0.704300,36.435070,0.000195
7d46aabd-4b84-4dc5-85d1-2b4b3aac49ad,MLOLONGO PRI SCH,EASTERN,MACHAKOS,MACHAKOS,-1.388401,36.935328,0.000218
...,...,...,...,...,...,...,...
c84f54bd-6a9a-4e9a-8cf2-c5dd4b372f01,DAVA INTEGRATED PRI SCH,NORTH EASTERN,MANDERA,MANDERA,3.953030,41.860900,401.815377
b65c396f-2777-4ccc-880f-ecc6d699fb57,DAVA SPECIAL UNIT,NORTH EASTERN,MANDERA,MANDERA,3.953030,41.860900,401.815377
e81a8321-55e8-4efd-a955-1e4649c6f3c6,BORDER VIEW ACADEMY PRI SCH,NORTH EASTERN,MANDERA,MANDERA,3.942400,41.867270,402.275520
41111108-34ef-42ae-84df-e21fe2338eff,BURUBURU PRI SCH,NORTH EASTERN,MANDERA,MANDERA,3.947800,41.868850,402.566618
2c3dfd34-7471-437f-9276-ebdaf6ae324b,B.P.ONE PRI SCH,NORTH EASTERN,MANDERA,MANDERA,3.969920,41.886510,404.986109

In [68]:
df_kenya_liquid_fixed = pd.read_csv(f'{fixed_data_dir}/kenya_liquid_fixed.csv', low_memory=False)
df_kenya_liquid_fixed

# use the uuid as primary key/index
df_kenya_liquid_fixed.set_index('uuid', inplace=True)
df_kenya_liquid_fixed

,name,admin2,admin3,admin4,lat,lon
uuid,,,,,,
801dbf2c-c795-4e4d-8e1f-726fbf583c20,Southend academy,WESTERN,BUNGOMA,BUNGOMA,0.562360,34.561880
0c9a96ac-3c87-4961-b1ee-0f930b4f1a0a,Joy shiru pri sch,NAIROBI,NAIROBI,NAIROBI,-1.265244,36.750676
302367ed-7a50-4069-aa91-7a6a70a779e3,St edwards high sch,NAIROBI,STAREHE,NaN,-1.272549,36.822084
51baf53c-1aa1-4105-914f-a0cfca56aefb,Naivasha pri boarding,RIFT VALLEY,NAKURU,NAKURU,-0.704300,36.435070
7d46aabd-4b84-4dc5-85d1-2b4b3aac49ad,Mlolongo pri sch,EASTERN,MACHAKOS,MACHAKOS,-1.388401,36.935328
...,...,...,...,...,...,...
c84f54bd-6a9a-4e9a-8cf2-c5dd4b372f01,Dava integrated pri sch,NORTH EASTERN,MANDERA,MANDERA,3.953030,41.860900
b65c396f-2777-4ccc-880f-ecc6d699fb57,Dava special unit,NORTH EASTERN,MANDERA,MANDERA,3.953030,41.860900
e81a8321-55e8-4efd-a955-1e4649c6f3c6,Border view academy pri sch,NORTH EASTERN,MANDERA,MANDERA,3.942400,41.867270
41111108-34ef-42ae-84df-e21fe2338eff,Buruburu pri sch,NORTH EASTERN,MANDERA,MANDERA,3.947800,41.868850
2c3dfd34-7471-437f-9276-ebdaf6ae324b,B.p.one pri sch,NORTH EASTERN,MANDERA,MANDERA,3.969920,41.886510

In [92]:
joined = df_kenya_liquid_fixed.join(df_kenya_liquid_uuid, lsuffix='_fixed')
qa_df = joined[['lat', 'Latitude', 'lon', 'Longitude']]
qa_df

                                           lat  Latitude        lon  Longitude
uuid
801dbf2c-c795-4e4d-8e1f-726fbf583c20  0.562360  0.562360  34.561880  34.561880
0c9a96ac-3c87-4961-b1ee-0f930b4f1a0a -1.265244 -1.265244  36.750676  36.750676
302367ed-7a50-4069-aa91-7a6a70a779e3 -1.272549 -1.272549  36.822084  36.822084
51baf53c-1aa1-4105-914f-a0cfca56aefb -0.704300 -0.704300  36.435070  36.435070
7d46aabd-4b84-4dc5-85d1-2b4b3aac49ad -1.388401 -1.388401  36.935328  36.935328
...                                        ...       ...        ...        ...
c84f54bd-6a9a-4e9a-8cf2-c5dd4b372f01  3.953030  3.953030  41.860900  41.860900
b65c396f-2777-4ccc-880f-ecc6d699fb57  3.953030  3.953030  41.860900  41.860900
e81a8321-55e8-4efd-a955-1e4649c6f3c6  3.942400  3.942400  41.867270  41.867270
41111108-34ef-42ae-84df-e21fe2338eff  3.947800  3.947800  41.868850  41.868850
2c3dfd34-7471-437f-9276-ebdaf6ae324b  3.969920  3.969920  41.886510  41.886510

[32485 rows x 4 columns]

In [98]:
# filter to only the changed records
changed_lat = qa_df['lat'] != qa_df['Latitude']
changed_lat

uuid
801dbf2c-c795-4e4d-8e1f-726fbf583c20    False
0c9a96ac-3c87-4961-b1ee-0f930b4f1a0a    False
302367ed-7a50-4069-aa91-7a6a70a779e3    False
51baf53c-1aa1-4105-914f-a0cfca56aefb    False
7d46aabd-4b84-4dc5-85d1-2b4b3aac49ad    False
                                        ...
c84f54bd-6a9a-4e9a-8cf2-c5dd4b372f01     True
b65c396f-2777-4ccc-880f-ecc6d699fb57     True
e81a8321-55e8-4efd-a955-1e4649c6f3c6    False
41111108-34ef-42ae-84df-e21fe2338eff    False
2c3dfd34-7471-437f-9276-ebdaf6ae324b     True
Length: 32485, dtype: bool

In [100]:
changed_lon = qa_df['lon'] != qa_df['Longitude']
changed_lon

uuid
801dbf2c-c795-4e4d-8e1f-726fbf583c20    False
0c9a96ac-3c87-4961-b1ee-0f930b4f1a0a    False
302367ed-7a50-4069-aa91-7a6a70a779e3     True
51baf53c-1aa1-4105-914f-a0cfca56aefb    False
7d46aabd-4b84-4dc5-85d1-2b4b3aac49ad     True
                                        ...
c84f54bd-6a9a-4e9a-8cf2-c5dd4b372f01    False
b65c396f-2777-4ccc-880f-ecc6d699fb57    False
e81a8321-55e8-4efd-a955-1e4649c6f3c6    False
41111108-34ef-42ae-84df-e21fe2338eff    False
2c3dfd34-7471-437f-9276-ebdaf6ae324b     True
Length: 32485, dtype: bool

In [101]:
tmp = qa_df[changed_lat]
tmp[changed_lon]
# so about only about 712 out of the original 32K records have modified locations

<ipython-input-101-086472d1f37f>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tmp[changed_lon]

                                           lat  Latitude        lon  Longitude
uuid
d16901d0-1e5e-462c-819d-d9d9711926cd -1.189110 -1.189110  36.931377  36.931377
a2bdccec-8df1-46ad-addc-c2b081d423ea -1.203788 -1.203788  36.917892  36.917892
15472286-5658-4699-81bd-9cfa4d3be8cf -0.476349 -0.476349  39.646197  39.646197
6ff1aa83-ac7a-4dfc-a6ca-2fad2a2c745b -1.206673 -1.206673  36.931310  36.931310
860019bc-f9e9-4d1f-b705-2c85ae7b2931 -1.416330 -1.416330  36.710528  36.710528
...                                        ...       ...        ...        ...
5e6f48fb-d6da-4fb9-8a3c-0ede8c597cbe  3.711890  3.711890  34.863660  34.863660
48ae9a7c-5608-4262-a133-07ca4a564451  3.834130  3.834130  41.526710  41.526710
aaa3beb8-fad7-4e21-af89-7a20cdff5f40  3.932720  3.932720  41.844190  41.844190
e7900178-5d80-4ac3-ac17-b8661baf4bae  3.945370  3.945370  41.845460  41.845460
2c3dfd34-7471-437f-9276-ebdaf6ae324b  3.969920  3.969920  41.886510  41.886510

[712 rows x 4 columns]

In [46]:
df_kenya_moe = pd.read_csv(f'{data_dir}/moe_schools.csv', low_memory=False)
df_kenya_moe['country_code'] = 'KE'
df_kenya_moe

,Name of School,Level of Education,Status of School,Province,District,Division,Location,Costituency,lat,lon,country_code
0,TAMBAYA PRIMARY SCHOOL,PRIMARY SCHOOL,PUBLIC,CENTRAL,NYERI,MUKURWE-INI,GAKINDU,MUKURWE-INI,-0.525169,37.017411,KE
1,TAMBAYA PRIMARY SCHOOL - SPECIAL UNIT,PRIMARY SCHOOL,PUBLIC,CENTRAL,NYERI,MUKURWE-INI,GAKINDU,MUKURWE-INI,-0.525056,37.018209,KE
2,SHINING STAR ACADEMY PRI,PRIMARY SCHOOL,PRIVATE,CENTRAL,NYERI,MUKURWE-INI,GAKINDU,MUKURWE-INI,-0.521132,37.013351,KE
3,GAIKUNDO PRIMARY SCHOOL,PRIMARY SCHOOL,PUBLIC,CENTRAL,NYERI,MUKURWE-INI,GAKINDU,MUKURWE-INI,-0.539896,37.001090,KE
4,WANJITHI PRI,PRIMARY SCHOOL,PUBLIC,CENTRAL,NYERI,MUKURWE-INI,GAKINDU,MUKURWE-INI,-0.550317,37.001616,KE
...,...,...,...,...,...,...,...,...,...,...,...
31224,SOWENE PRIMARY,PRIMARY SCHOOL,PUBLIC,COAST,TAITA TAVETA,TAVETA,BOMANI,TAVETA,-3.389600,37.671410,KE
31225,LEISURE ACADEMY PRIMARY,PRIMARY SCHOOL,PRIVATE,COAST,TAITA TAVETA,TAVETA,BOMANI,TAVETA,-3.386770,37.668590,KE
31226,TAVETA JUNIOR ACADEMY,PRIMARY SCHOOL,PRIVATE,COAST,TAITA TAVETA,TAVETA,BOMANI,TAVETA,-3.382530,37.676060,KE
31227,LESSESIA PRIMARY,PRIMARY SCHOOL,PUBLIC,COAST,TAITA TAVETA,TAVETA,BOMANI,TAVETA,-3.366570,37.664590,KE
31228,ALFATTAH PRIMARY,PRIMARY SCHOOL,PUBLIC,COAST,TAITA TAVETA,TAVETA,BOMANI,TAVETA,-3.389400,37.673770,KE

In [47]:
df_rwanda = pd.read_excel('../../data/UNICE_schools_raw_2020_Jun/Rwandan Schools_GIS DATA_4G coverage status.xlsx')
df_rwanda['country_code'] = 'RW'
df_rwanda

,NO,PROVINCE,DISTRICT,SECTOR,CELL,VILLAGE,School Name,Settings in School,PointID (GPS),Degree,Minute,Seconds,Degree.1,Minute.1,Seconds.1,Description,Latitude,Longitude,4G Status,country_code
0,1,City of Kigali,Nyarugenge,Gitega,Akabahizi,Iterambere,E.M CYAPEPE,Preprimary,049,1,56.0,41.5,30,3.0,7.8,School Center,-1.944861,30.052167,covered,RW
1,2,City of Kigali,Nyarugenge,Gitega,Akabahizi,Gihanga,E.M ITETERO,Preprimary,056,1,56.0,56.1,30,3.0,12.7,School Center,-1.948917,30.053528,covered,RW
2,3,City of Kigali,Nyarugenge,Gitega,Akabahizi,Iterambere,G.S CYAHAFI,9 YBE,048,1,56.0,41.0,30,3.0,12.0,NEAR THE ENTRANCE,-1.944722,30.053333,covered,RW
3,4,City of Kigali,Nyarugenge,Gitega,Kinyange,Uburezi,E.P GITEGA,Primary,051,1,57.0,35.2,30,3.0,22.7,HEAD TEACHER OFFICE,-1.959778,30.056306,covered,RW
4,5,City of Kigali,Nyarugenge,Gitega,Kora,Kivumu,ETO MUHAZI I,Secondary A Level,047,1,57.0,9.8,30,3.0,26.7,HEAD TEACHER OFFICE,-1.952722,30.057417,covered,RW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4229,4230,Northern,Burera,Rwerere,Gacundura,Gacundura,E.P GACUNDURA,Primary,64,1,30.0,9.3,29,51.0,22.9,FLAG POLE,-1.502583,29.856361,covered,RW
4230,4231,Northern,Burera,Rwerere,Gashoro,Rwerere,G.S CYAPA,12 YBE,68,1,29.0,50.7,29,51.0,47.4,School Center,-1.497417,29.863167,covered,RW
4231,4232,Northern,Burera,Rwerere,Gashoro,Cyapa,E.M CYAPA,Preprimary,070,1,29.0,52.0,29,51.0,47.8,School Center,-1.497778,29.863278,covered,RW
4232,4233,Northern,Burera,Rwerere,Ruconsho,Ruconsho,E.P RWERERE,Primary,66,1,31.0,47.0,29,52.0,55.0,FLAG POLE,-1.529722,29.881944,covered,RW
4233,4234,Northern,Burera,Rwerere,Rugali,Mucaca,E.P RUGALI,Primary,69,1,32.0,31.0,29,52.0,22.3,School Center,-1.541944,29.872861,covered,RW

In [39]:
df_kenya_usaid = pd.read_csv(f'{data_dir}/usaid_schools.csv', low_memory=False)
df_kenya_usaid['country_code'] = 'KE'
df_kenya_usaid

,Region,county_id,county,county_code,subCounty_id,subCounty,subsCounty_code,zone_id,zone,zone_code,school_id,school,verified_latitude,verified_longitude,school_code,tusome_code,REGULAR / SNE,PUBLIC / APBET / HI / VI / HI&VI,2019_Active / Inactive status,country_code
0,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,NaN,Chebunyor,NaN,NaN,13.0,1101013.0,REGULAR,PUBLIC,Active,KE
1,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,9CWwjhDS,Kabarbarma,-1.259261,36.803921,1.0,1101001.0,REGULAR,PUBLIC,Active,KE
2,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,R2wzR2g4,Kabochony,0.440002,35.800895,2.0,1101002.0,REGULAR,PUBLIC,Active,KE
3,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,nemmFtXC,Kapkiai,0.426389,35.805504,3.0,1101003.0,REGULAR,PUBLIC,Active,KE
4,Eldoret,ep8yqMKT,Baringo,1,dKpabrnG,Baringo Central,1,SyYZ2NEn,Chapchap,1,NaN,Kapkoimet,NaN,NaN,14.0,1101014.0,REGULAR,PUBLIC,Active,KE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26115,Nairobi,YFZjN4qd,Nyandarua,35,cSaQj4aa,Nyandarua West,7,UEnbPUHp,Ol Joro Orok,2,VXhwMAjT,Riverside,0.011700,36.357299,24.0,35702024.0,REGULAR,PUBLIC,Active,KE
26116,Nairobi,YFZjN4qd,Nyandarua,35,cSaQj4aa,Nyandarua West,7,UEnbPUHp,Ol Joro Orok,2,Pw4HvM8t,Uhuru,-0.143029,36.311293,25.0,35702025.0,REGULAR,PUBLIC,Active,KE
26117,Nairobi,YFZjN4qd,Nyandarua,35,cSaQj4aa,Nyandarua West,7,UEnbPUHp,Ol Joro Orok,2,paM6wjfP,Uiguano,-0.173542,36.385639,26.0,35702026.0,REGULAR,PUBLIC,Active,KE
26118,Nairobi,YFZjN4qd,Nyandarua,35,cSaQj4aa,Nyandarua West,7,UEnbPUHp,Ol Joro Orok,2,3xxcCXh6,Weru,-0.139374,36.380180,27.0,35702027.0,REGULAR,PUBLIC,Active,KE
26119,Nairobi,YFZjN4qd,Nyandarua SNE,35,xQaGMtX9,Nyandarua South,6,9AAtWvX4,Engineer,1,zrqwvsSx,Nyandarua Sch For Deaf,NaN,NaN,17.0,35601017.0,SNE,HI,Active,KE

In [48]:
df_zimbabwe = pd.read_excel('../../data/UNICE_schools_raw_2020_Jun/Zimbabwe schools complete data.xlsx')
df_zimbabwe['country_code'] = 'ZW'
df_zimbabwe

,Schoolnumber,Name,SchoolLevel,Province,latitude,longitude,Tot_comp_Student,Enrolment,_tot_func_computers,connectiontype,country_code
0,1001,ADMIRAL TAIT,Primary,Harare,-17.8264,31.0897,27.0,2390,35,ADSL,ZW
1,1002,ALEXANDRA PARK,Primary,Harare,-17.7915,31.0557,26.0,983,50,None,ZW
2,1003,ALFRED BEIT PRIMARY,Primary,Harare,-17.7881,31,6.0,1784,9,ADSL,ZW
3,1004,ARDBENNIE,Primary,Harare,-17.8767,31.035,25.0,1240,29,ADSL,ZW
4,1005,AVONDALE,Primary,Harare,-17.7917,31.0341,221.0,1708,309,Fibre Optic,ZW
...,...,...,...,...,...,...,...,...,...,...,...
9620,1618,SUNNY DAY CHRISTIAN,Primary,Harare,(blank),(blank),12.0,154,14,Fibre Optic,ZW
9621,1950,PAGOMO PRIMARY,Primary,Manicaland,(blank),(blank),10.0,62,10,None,ZW
9622,4571,ZIMBABWE NATIONAL DEFENCE COLLEGE,Primary,Mashonaland Central,(blank),(blank),NaN,316,2,Fibre Optic,ZW
9623,14816,WASHINGTON HILLS HIGH SCHOOL,Secondary,Mashonaland West,(blank),(blank),30.0,331,33,Fibre Optic,ZW
9624,9326,PARKLANDS PRIMARY SCHOOL,Primary,Mashonaland West,(blank),(blank),0.0,486,1,None,ZW