In [1]:
import logging
import pandas as pd
from iso3166 import countries
from csv import QUOTE_NONNUMERIC
from unicef_schools_attribute_cleaning.pandas.standardize_column_names import standardize_column_names
from unicef_schools_attribute_cleaning.pandas.dataframe_cleaner import dataframe_cleaner

# make INFO logs visible
logging.basicConfig(level=logging.INFO)

In [2]:
src_df = pd.read_excel('../../data/UNICE_schools_raw_2020_Jun/Zimbabwe schools complete data.xlsx')
# src_df = pd.read_csv('../../data/unicef_fixed/zimbabwe_original_uuid.csv', low_memory=False)

src_df

,Schoolnumber,Name,SchoolLevel,Province,latitude,longitude,Tot_comp_Student,Enrolment,_tot_func_computers,connectiontype
0,1001,ADMIRAL TAIT,Primary,Harare,-17.8264,31.0897,27.0,2390,35,ADSL
1,1002,ALEXANDRA PARK,Primary,Harare,-17.7915,31.0557,26.0,983,50,None
2,1003,ALFRED BEIT PRIMARY,Primary,Harare,-17.7881,31,6.0,1784,9,ADSL
3,1004,ARDBENNIE,Primary,Harare,-17.8767,31.035,25.0,1240,29,ADSL
4,1005,AVONDALE,Primary,Harare,-17.7917,31.0341,221.0,1708,309,Fibre Optic
...,...,...,...,...,...,...,...,...,...,...
9620,1618,SUNNY DAY CHRISTIAN,Primary,Harare,(blank),(blank),12.0,154,14,Fibre Optic
9621,1950,PAGOMO PRIMARY,Primary,Manicaland,(blank),(blank),10.0,62,10,None
9622,4571,ZIMBABWE NATIONAL DEFENCE COLLEGE,Primary,Mashonaland Central,(blank),(blank),NaN,316,2,Fibre Optic
9623,14816,WASHINGTON HILLS HIGH SCHOOL,Secondary,Mashonaland West,(blank),(blank),30.0,331,33,Fibre Optic
9624,9326,PARKLANDS PRIMARY SCHOOL,Primary,Mashonaland West,(blank),(blank),0.0,486,1,None

In [3]:
country = countries.get('ZW')
with open('zimbabwe_columns_report.txt', mode='w', encoding='utf-8') as filehandle:
    df = dataframe_cleaner(
        dataframe=src_df,
        removed_columns_report=filehandle,
        country=country
    )
df

INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:copying dataframe...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:standardizing column names...
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:uuid column not found, generating uuid4
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:renaming columns: {'Enrolment': 'num_students',
 'Name': 'name',
 'Province': 'admin2',
 'SchoolLevel': 'educ_level',
 'Schoolnumber': 'description',
 '_tot_func_computers': 'num_computers',
 'connectiontype': 'type_connectivity',
 'latitude': 'lat',
 'longitude': 'lon'}
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:adding 36 columns from schema: ['admin0',
 'admin1',
 'admin3',
 'admin4',
 'admin_code',
 'admin_id',
 'address',
 'address2',
 'phone_number',
 'person_contact',
 'email',
 'postal_code',
 'altitude',
 'gps_confidence',
 'date',
 'num_teachers',
 'connectivity',
 'speed_connectivity',
 'latency_connectivity',
 'availability_connectivity',
 'type_school',
 'environment',
 'num_classrooms',
 'num_sections',
 'water',
 'electricity',
 'num_latrines',
 'last_update',
 'tower_dist',
 'tower_type_service',
 'tower_type',
 'tower_code',
 'tower_latitude',
 'tower_longitude',
 'is_invalid',
 'is_invalid_reason']
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:removing columns: ['Tot_comp_Student'] (not in School schema)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:validate each school row to the schema...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:lookup GADM areas by lat,lon...
INFO:unicef_schools_attribute_cleaning.geocoding.GADMLoader:cache hit for: https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_ZWE_gpkg.zip
INFO:unicef_schools_attribute_cleaning.geocoding.GADMLoader:converting geopackage file...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:processing each lat,lon into GADM area...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=BUMHIRA, lat,lng=-17.88638,32.95592 https://www.openstreetmap.org/#map=18/-17.88638/32.95592 (uuid=7c8d3648-ed4b-4ec5-a3a3-2096abe5b0c4)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=CHAYAMITI, lat,lng=-19.6676,32.86055 https://www.openstreetmap.org/#map=18/-19.6676/32.86055 (uuid=1b1cb2fe-9d1c-4bc8-859f-56656ec5d442)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=DEMENI, lat,lng=-20.09132,32.92432 https://www.openstreetmap.org/#map=18/-20.09132/32.92432 (uuid=1dc46090-5a3f-4ae6-8a02-628d55993428)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=MUKUMBURA, lat,lng=-16.2008,31.70187 https://www.openstreetmap.org/#map=18/-16.2008/31.70187 (uuid=aab30aed-ed4b-44e6-a3b8-0f56280965b0)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=GOMO, lat,lng=-16.30827,31.8467 https://www.openstreetmap.org/#map=18/-16.30827/31.8467 (uuid=b4ae907f-54c2-41f4-9a3c-01e2e52862aa)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=SINAMATELLA, lat,lng=-18.05964,26.61752 https://www.openstreetmap.org/#map=18/-18.05964/26.61752 (uuid=d87307b3-38fd-4fc8-a462-4194c6ee603f)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=IMPALI PRIMARY, lat,lng=0,0 https://www.openstreetmap.org/#map=18/0/0 (uuid=8ed587b0-5abe-4cee-99e5-969f8834c0ed)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=IMPALI PRIMARY, lat,lng=0,0 https://www.openstreetmap.org/#map=18/0/0 (uuid=8ed587b0-5abe-4cee-99e5-969f8834c0ed)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=AMR SISTERS ROMAN CATHOLIC, lat,lng=0,0 https://www.openstreetmap.org/#map=18/0/0 (uuid=d4151c5e-2b40-40f4-8613-03f0d60de6c4)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=AMR SISTERS ROMAN CATHOLIC, lat,lng=0,0 https://www.openstreetmap.org/#map=18/0/0 (uuid=d4151c5e-2b40-40f4-8613-03f0d60de6c4)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:buffering location by 5.0km for school name=KUSILE GOVERNMENT PRIMARY, lat,lng=0,0 https://www.openstreetmap.org/#map=18/0/0 (uuid=d69eb899-f033-4ed1-b1a8-b6e2215f04fa)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=KUSILE GOVERNMENT PRIMARY, lat,lng=0,0 https://www.openstreetmap.org/#map=18/0/0 (uuid=d69eb899-f033-4ed1-b1a8-b6e2215f04fa)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:1706 invalid records found. See column is_invalid_reason for details.
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:readying pandas data types...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:done

,address,address2,admin0,admin1,admin2,admin3,admin4,admin_code,admin_id,altitude,...,tower_code,tower_dist,tower_latitude,tower_longitude,tower_type,tower_type_service,type_connectivity,type_school,uuid,water
0,None,None,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",None,...,None,None,None,None,None,None,DSL,None,19d8ad40-a2f5-4230-9e0f-b48a85c221bf,False
1,None,None,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",None,...,None,None,None,None,None,None,None,None,1477487d-9252-4cde-9dcc-74478ce1abc5,False
2,None,None,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",None,...,None,None,None,None,None,None,DSL,None,669dc828-54c8-4966-b9c5-0469669ce44b,False
3,None,None,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",None,...,None,None,None,None,None,None,DSL,None,d31b2187-168a-4665-bd3b-9f0ebb8cc257,False
4,None,None,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",None,...,None,None,None,None,None,None,Fiber,None,582bbff1-f542-4583-98a8-e2830143859d,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9620,None,None,<NA>,<NA>,<NA>,None,None,<NA>,"3.6,ZWE,GID_2=nan",None,...,None,None,None,None,None,None,Fibre Optic,None,82c1da58-1ee1-4c73-9f32-bd5a807bdf3d,<NA>
9621,None,None,<NA>,<NA>,<NA>,None,None,<NA>,"3.6,ZWE,GID_2=nan",None,...,None,None,None,None,None,None,None,None,8f49a01c-583e-4f26-9ba0-dd9b6415593b,<NA>
9622,None,None,<NA>,<NA>,<NA>,None,None,<NA>,"3.6,ZWE,GID_2=nan",None,...,None,None,None,None,None,None,Fibre Optic,None,32d22ccd-fdc1-4cdf-8758-ec673b41f29d,<NA>
9623,None,None,<NA>,<NA>,<NA>,None,None,<NA>,"3.6,ZWE,GID_2=nan",None,...,None,None,None,None,None,None,Fibre Optic,None,47bc127f-127f-4084-9353-7d2ee171b135,<NA>
9624,None,None,<NA>,<NA>,<NA>,None,None,<NA>,"3.6,ZWE,GID_2=nan",None,...,None,None,None,None,None,None,None,None,ce64393f-3447-467b-897f-7280745abc3c,<NA>

In [4]:
df.to_csv('zimbabwe_cleaned.csv', quoting=QUOTE_NONNUMERIC, index=False)

In [5]:
# open in LibreOffice, Excel, other
!open zimbabwe_cleaned.csv