In [1]:
import logging
import pandas as pd
from iso3166 import countries
from csv import QUOTE_NONNUMERIC
from unicef_schools_attribute_cleaning.pandas.standardize_column_names import standardize_column_names
from unicef_schools_attribute_cleaning.pandas.dataframe_cleaner import dataframe_cleaner

# make INFO logs visible
logging.basicConfig(level=logging.INFO)

In [2]:
src_df = pd.read_excel('../../data/UNICE_schools_raw_2020_Jun/Zimbabwe schools complete data.xlsx')
# src_df = pd.read_csv('../../data/unicef_fixed/zimbabwe_original_uuid.csv', low_memory=False)

src_df

,Schoolnumber,Name,SchoolLevel,Province,latitude,longitude,Tot_comp_Student,Enrolment,_tot_func_computers,connectiontype
0,1001,ADMIRAL TAIT,Primary,Harare,-17.8264,31.0897,27.0,2390,35,ADSL
1,1002,ALEXANDRA PARK,Primary,Harare,-17.7915,31.0557,26.0,983,50,None
2,1003,ALFRED BEIT PRIMARY,Primary,Harare,-17.7881,31,6.0,1784,9,ADSL
3,1004,ARDBENNIE,Primary,Harare,-17.8767,31.035,25.0,1240,29,ADSL
4,1005,AVONDALE,Primary,Harare,-17.7917,31.0341,221.0,1708,309,Fibre Optic
...,...,...,...,...,...,...,...,...,...,...
9620,1618,SUNNY DAY CHRISTIAN,Primary,Harare,(blank),(blank),12.0,154,14,Fibre Optic
9621,1950,PAGOMO PRIMARY,Primary,Manicaland,(blank),(blank),10.0,62,10,None
9622,4571,ZIMBABWE NATIONAL DEFENCE COLLEGE,Primary,Mashonaland Central,(blank),(blank),NaN,316,2,Fibre Optic
9623,14816,WASHINGTON HILLS HIGH SCHOOL,Secondary,Mashonaland West,(blank),(blank),30.0,331,33,Fibre Optic
9624,9326,PARKLANDS PRIMARY SCHOOL,Primary,Mashonaland West,(blank),(blank),0.0,486,1,None

In [3]:
country = countries.get('ZW')
df = dataframe_cleaner(dataframe=src_df.head(1000), country=country)
df

INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:copying dataframe...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:standardizing column names...
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:uuid column not found, generating uuid4
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:renaming columns: {'Enrolment': ('num_students', 'fuzzy match on alias column: enrollment 95%'),
 'Name': ('name', 'fuzzy match 100%'),
 'Province': ('admin2', 'alias exact match'),
 'SchoolLevel': ('educ_level', 'fuzzy match on alias column: school level 96%'),
 'Schoolnumber': ('description',
                  'fuzzy match on alias column: school number 96%'),
 '_tot_func_computers': ('num_computers',
                         'fuzzy match on alias column: tot_func_computers 97%'),
 'connectiontype': ('type_connectivity', 'alias exact match'),
 'latitude': ('lat', 'alias exact match'),
 'longitude': ('lon', 'alias exact match')}
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:adding 34 columns from schema: ['admin0',
 'admin1',
 'admin3',
 'admin4',
 'admin_code',
 'admin_id',
 'address',
 'address2',
 'phone_number',
 'person_contact',
 'email',
 'postal_code',
 'altitude',
 'gps_confidence',
 'date',
 'num_teachers',
 'connectivity',
 'speed_connectivity',
 'latency_connectivity',
 'availability_connectivity',
 'type_school',
 'environment',
 'num_classrooms',
 'num_sections',
 'water',
 'electricity',
 'num_latrines',
 'last_update',
 'tower_dist',
 'tower_type_service',
 'tower_type',
 'tower_code',
 'tower_latitude',
 'tower_longitude']
INFO:unicef_schools_attribute_cleaning.pandas.standardize_column_names:removing columns: ['Tot_comp_Student'] (not in School schema)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:filtering rows missing lat,lon...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:validating each school row to the schema...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:lookup GADM areas by lat,lon...
INFO:unicef_schools_attribute_cleaning.geocoding.GADMLoader:cache hit for: https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_ZWE_gpkg.zip
INFO:unicef_schools_attribute_cleaning.geocoding.GADMLoader:converting geopackage file...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:processing each lat,lon...
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=BUMHIRA, lat,lng=-17.88638,32.95592 https://www.openstreetmap.org/#map=18/-17.88638/32.95592 (uuid=5bbcca54-6b1f-4e6c-a063-35ff12ee5c7c)
WARNING:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:school outside of GADM boundaries name=CHAYAMITI, lat,lng=-19.6676,32.86055 https://www.openstreetmap.org/#map=18/-19.6676/32.86055 (uuid=2be14506-ab12-4c62-99b5-77bcabdb5f9d)
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:readying pandas data types...
INFO:unicef_schools_attribute_cleaning.pandas.dataframe_cleaner:1000 source rows -> 969 cleaned rows

,country_code,admin0,admin1,admin2,admin3,admin4,admin_code,admin_id,name,address,...,description,last_update,tower_dist,tower_type_service,tower_type,tower_code,tower_latitude,tower_longitude,is_private,uuid
0,ZW,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",ADMIRAL TAIT,None,...,1001,None,None,None,None,None,None,None,True,ec52094a-4585-4196-b538-b68ad00f66dc
1,ZW,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",ALEXANDRA PARK,None,...,1002,None,None,None,None,None,None,None,True,97d32e8d-6586-42a2-97ae-42a2f76b347a
2,ZW,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",ALFRED BEIT PRIMARY,None,...,1003,None,None,None,None,None,None,None,True,e93f42be-8907-4093-bcc6-0eac1d941395
3,ZW,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",ARDBENNIE,None,...,1004,None,None,None,None,None,None,None,True,241c56fb-4790-420a-900a-4af6b54a6ccb
4,ZW,Zimbabwe,Harare,Harare,None,None,ZWE.2.1_1,"3.6,ZWE,GID_2=ZWE.2.1_1",AVONDALE,None,...,1005,None,None,None,None,None,None,None,True,6a6d59c7-ea02-4336-819e-c5e0114a4bf9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ZW,Zimbabwe,Manicaland,Mutare,None,None,ZWE.3.5_1,"3.6,ZWE,GID_2=ZWE.3.5_1",KUSENA,None,...,2717,None,None,None,None,None,None,None,True,9e2d1e8d-58a9-48c5-a0e3-d807774dcebc
996,ZW,Zimbabwe,Manicaland,Makoni,None,None,ZWE.3.4_1,"3.6,ZWE,GID_2=ZWE.3.4_1",DOMBORESHATO,None,...,2718,None,None,None,None,None,None,None,True,9708e446-2862-4776-afe8-0c2517ec7d99
997,ZW,Zimbabwe,Manicaland,Nyanga,None,None,ZWE.3.7_1,"3.6,ZWE,GID_2=ZWE.3.7_1",DANDADZI PRIMARY SCHOOL,None,...,2719,None,None,None,None,None,None,None,True,63321f9a-5fce-484c-92ff-f54f1bdec218
998,ZW,Zimbabwe,Manicaland,Buhera,None,None,ZWE.3.1_1,"3.6,ZWE,GID_2=ZWE.3.1_1",CHAPANDUKA,None,...,2720,None,None,None,None,None,None,None,True,9d936a45-1754-4d36-b220-5e7bc955ab2c
999,ZW,Zimbabwe,Manicaland,Buhera,None,None,ZWE.3.1_1,"3.6,ZWE,GID_2=ZWE.3.1_1",ROMOREHOTO,None,...,2721,None,None,None,None,None,None,None,True,2bc430af-53c1-40d9-bc68-983b7e3bd5ff

In [4]:
df.to_csv('zimbabwe_cleaned.csv', quoting=QUOTE_NONNUMERIC, index=False)

In [5]:
# open in LibreOffice, Excel, other
!open zimbabwe_cleaned.csv